@startuml

actor "Пользователь" as U
participant "Front App" as F
participant "Backend API" as B
participant "Keycloak" as K

U -> F: login()
F -> F: генерация code_verifier
F -> F: хеширование code_verifier в code_challenge
F -> K: запрос кода авторизации с передачей code_challenge и способа хеширования
K -> K: привязка code_challenge и способа хеширования к сессии пользователя
K --> U: редирект на запрос авторизации
U -> K: согласие на аутентификациию
K --> F: передача кода авторизации
F -> K: запрос на получение токена с передачей кода авторизации и code_verifier
K -> K: валидация кода авторизации и code_verifier
K --> F: возвращение токена
F -> B: запрос данных с передачей токена
B -> K: запрос публичного ключа
K --> B: передача публичного ключа
B -> B: верификация токену
alt токен верифицирован
    B --> F: ответ 200 с отчетом пользователя
else токен не прошел верифицию
    B --> F: ответ 401
end


@enduml